# Generated by Django 3.2.23 on 2023-12-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentId', models.AutoField(primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('RegistrationNo', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Course', models.CharField(max_length=50)),
            ],
        ),
    ]
